### ISSUE TITLE
Add configuration section for average price

### ISSUE THREAD

**Issue by kumar-ish** [jkwill87/stonky#1]
Hi,

Would it be possible to add a config section that you can write the average price that you bought your share holdings onto (so that you can see how much your P/L is overall)? Something along these lines in `.stonky.cfg`:

```
[avg_price]
AMZN=2367.92
VGRO.TO=24.81
BTC-USD=11.983.70
```

It won't take into account dividends etc. but it's still good as a guide and I'd personally find it very useful. If this is something that you'd like, I can add make a pull request for it myself?

This is a great and super useful project; thanks a lot!

**Comment by jkwill87** [comment]
I don't think being able to set the average buying price would have any effects on the output

Just to recap in case its not clear:

- "Watchlist" just shows ticker tapes for the listed securities
- "Positions" report changes for the day
- "Profit and Loss" reports the sum of changes for the day
- "Balances" shows a sum of all held securities plus reported cash

**Comment by kumar-ish** [comment]
Sorry, I should have been more clear. The section would be added in addition to code for calculating an `OVERALL` section, which would print something like this in the output, detailing the overall P/L on your holdings:
```
OVERALL POSITIONS
AMZN 27.07% 3204.95
VGRO.TO 6.89% 1709.40
BTC-USD -20.00% -239.77
```
(the crunched up above is calcuated from the positions, average price data as in the original prices in my issue message, and current price)
