### ISSUE TITLE
Integration of Bitpanda

### ISSUE THREAD

**Issue by MMartin09** [jkwill87/stonky#10]
Stonky is really useful but a disadvantage is that it only supports Yahoo. For me it would be great if there would also be a support for Bitpanda. 
I wanted to ask if this would be a possible new feature of stonky if I start working at it.

**Comment by jkwill87** [comment]
> Stonky is really useful but a disadvantage is that it only supports Yahoo.

Why is that a disadvantage? What additional functionality would be added from integrating Bitpanda? From what I can tell it the service only supports a subset of securities supported by Yahoo Finance and requires authentication.

> For me it would be great if there would also be a support for Bitpanda.

You're certainly welcome to fork the repository and develop this for your purposes. To consider merging these changes upstream, however, please explain how they would have a broad general appeal to others. I need a compelling reason to justify adding the additional complexity to the project along with the liability for maintenance and support it would imply.

**Comment by MMartin09** [comment]
You are right. I will fork it and see in which direction the development goes.
