### ISSUE TITLE
Install Questions

### ISSUE THREAD

**Issue by m-a-c-k** [jkwill87/stonky#3]
More of a user issue, but having trouble configuring my .stonky.cfg file. It keeps loading the example. What are the install steps as far as setup.py build/install?

**Comment by jkwill87** [comment]
If stonky is loading the example config file you've installed it. The easiest way to load your own config file is to make a copy of [the example one](https://github.com/jkwill87/stonky/blob/master/stonky/__example.cfg), tweak it to your liking, then save it as `.stonky.cfg` in your home directory.

**Comment by m-a-c-k** [comment]
Thank you for the response. I did try and tweak the example file and saved as .stonky.cfg
When you say "home directory" you mean where stonky repo was cloned into?

**Comment by jkwill87** [comment]
> When you say "home directory" you mean where stonky repo was cloned into?

No, your user account's home directory. e.g. where you end up when you end up when you run `cd %HOMEPATH%` on Windows or `cd $HOME` on MacOS or Linux.

> Will i need to rebuild after?

Nope, this file is read at runtime. You can just edit the config file then re-run stonky.
