### ISSUE TITLE
ECB is not Forex prices

### ISSUE THREAD

**Issue by arzzen** [jkwill87/stonky#5]
https://github.com/jkwill87/stonky/blob/d603280936876b337ec8a772fc2cdc202b62f832/stonky/api.py#L58-L59

Hello, API exchangeratesapi.io did not provide forex prices, they provide only ECB exchange rates,
you should find another API source.

**Comment by jkwill87** [comment]
[v1.2.0](https://github.com/jkwill87/stonky/releases/tag/1.2.0) pulls current rates from Yahoo! finance. This is probably as good as it will get using unpaid providers.
